web:
  image: fengzhou/nginx-fuse
  devices:
    - /dev/fuse
  cap_add:
    - SYS_ADMIN
  ports:
    - "80:80"
  environment:
    - SSH_REMOTE_HOST=example.com
    - SSH_REMOTE_PATH=/remote/path
    - SSH_LOCAL_PATH=/ssh_path
    - SSH_REMOTE_USER=example
    - SSH_REMOTE_PASSWORD=password
    - FTP_REMOTE_HOST=example.com
    - FTP_REMOTE_PATH=/remote/path
    - FTP_LOCAL_PATH=/ftp_path
    - FTP_REMOTE_USER=example
    - FTP_REMOTE_PASSWORD=password
